### ISSUE TITLE
Error in qualUniform(x$ratio, x$count) :   Error: qualUniform() received negative or missing data!

### ISSUE THREAD

**Issue by Maithy15** [cbielow/PTXQC#121]
Hi,

Whenever I tried to run PTXQC on Phospho samples, I got this error "Error in qualUniform(x$ratio, x$count) :   Error: qualUniform() received negative or missing data!". I have attached the log. Could you please tell me why this is happening?

[report_v1.0.5.zip](https://github.com/cbielow/PTXQC/files/9439436/report_v1.0.5.zip)

Thanks
Maithy

**Comment by cbielow** [comment]
Hi Maithy,

This is a bug.
Could you please provide the msmsScans.txt. Then i can fix the problem.

For the time being, you can simply rename the msmsScans.txt to prevent the bug from occuring. You will however loose all metrics derived from this file until the bug is fixed.

Cheers Chris


Am 28.08.2022 12:06 schrieb Maithy15 ***@***.***>:

Hi,

Whenever I tried to run PTXQC on Phospho samples, I got
report_v1.0.5.zip<https://github.com/cbielow/PTXQC/files/9439436/report_v1.0.5.zip>
this error "Error in qualUniform(x$ratio, x$count) : Error: qualUniform() received negative or missing data!". I have attached the log. Could you please tell me why this is happening?

Thanks
Maithy

**Comment by Maithy15** [comment]
Hi Chris,

Thanks for the quick reply! Here is the msmsScasns.txt file https://fz-juelich.sciebo.de/s/lDc3I2fc4NOamtQ.

Thanks
Maithy

**Comment by cbielow** [comment]
Hi Maithy,

I realized you are using an older version of PTXQC (1.0.5 was released more than 2 years ago).
Using the latest 1.0.14 the report generations runs fine without any issues.
The bug was fixed in some previous version. 
Please update PTXQC. This should resolve your issue (if this somehow does not work, of course please report it here)

cheers
Chris
