### ISSUE TITLE
ITRAQ multinotch data

### ISSUE THREAD

**Issue by pwaridel** [cbielow/PTXQC#13]
Hello,
I was able to use PTXQC with some classical (HCD MS2 at high resolution) iTRAQ data acquired on a Fusion instrument. But when I use a multinotch method (MS2 CID at low resolution for identification, MS3 HCD at high resolution for reporter quantification, = Reporter ion MS3 in MaxQuant), PTXQC crashes when processing the data. Both classical and multinotch data were processed on the same computer with drag and drop setup. MaxQuant version is 1.5.3.30.
[Error-message.txt](https://github.com/cbielow/PTXQC/files/88685/Error-message.txt)

**Comment by cbielow** [comment]
Hi, thanks for reporting this.
PTXQC has never been tested with MS3 data and it seems the internal condition checks complain about
```Scan event distribution is not monotonically increasing!```

Quickfix: disable reading of MSMSscans in the yaml config file and re-run PTXQC. Some metrics will get lost, but the majority is still present.

Could you send me a link to a minimal dataset (which you upload somewhere) via email (address is in the package description file). I'll look into it.

**Comment by cbielow** [comment]
Thanks for sending the data.

The bug is fixed in 96df116.

Could you please verify that the bug is fixed? Thanks.

Explanation: it seems that when MS3 events are recorded between MS2 events, then MS2 events are not numbered consecutively in terms of their scan.event.number (but we observe gaps)
Solution: gaps are closed by PTXQC by just assigning consecutive numbers. This should have no side effects on the metrics directly, but makes judging the results a little harder, since MS3 events could take an 'arbitrary' amount of time.

**Comment by pwaridel** [comment]
Hi, this bug is fixed, but in the last version (0.70) I get another bug at the report level for all type of data:
the page 1 with summary of all parameters is empty

**Comment by cbielow** [comment]
The empty param page is fixed in  6322c99. Thanks for reporting!

Bug is fixed, closing this issue.
