### ISSUE TITLE
error after starting to work on EVD: Pep Missing Values

### ISSUE THREAD

**Issue by Leo838** [cbielow/PTXQC#30]
Thanks for developing this nice software. I have installed the latest version (v0.82.1) of PTXQC at the environment of R 3.3.2. It is running fine except a larger data set (~200 raw files). There it stopped right after working on EVD: Pep Missing Values and no PDF/Html reports generated. 

The message looks like this:
Starting to work on EVD: MS^2 Oversampling ...

Memory [MB] prior|after|max(diff) : 2707.2 | 2707.4 | 5362.7 (2656)

Duration: 10 s

... EVD: MS^2 Oversampling  done
Starting to work on EVD: Pep Missing Values ...
Error in array(STATS, dims[perm]) : 'dims' cannot be of length 0
Press any key to continue . . .

What could be the problem? If this step makes problem, could we skip this step and report only others that have passed through?

**Comment by Leo838** [comment]
I also tried to use the first release, but I got trouble installing it. 
It complained that "Biobase" was missing.
error message as following: 

> install_github("cbielow/PTXQC", ref="v0.69.3", build_vignettes = TRUE)
Downloading GitHub repo cbielow/PTXQC@v0.69.3
from URL https://api.github.com/repos/cbielow/PTXQC/zipball/v0.69.3
Installing PTXQC
Skipping 1 unavailable package: Biobase
"C:/Users/kpan/Documents/R/R-3.1.0/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD build  \
  "C:\Users\kpan\AppData\Local\Temp\RtmpOiiRmK\devtools16607a003078\cbielow-PTXQC-7a98a1f"  \
  --no-resave-data --no-manual 

* checking for file 'C:\Users\kpan\AppData\Local\Temp\RtmpOiiRmK\devtools16607a003078\cbielow-PTXQC-7a98a1f/DESCRIPTION' ... OK
* preparing 'PTXQC':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
Warning: running command '"C:/Users/kpan/DOCUME~1/R/R-31~1.0/bin/x64/Rcmd.exe" INSTALL -l "C:\Users\kpan\AppData\Local\Temp\Rtmp4GAMsN\Rinst21705ae349a4" --no-multiarch "C:/Users/kpan/AppData/Local/Temp/Rtmp4GAMsN/Rbuild2170113646e/PTXQC"' had status 1
      -----------------------------------
ERROR: dependency 'Biobase' is not available for package 'PTXQC'
* removing 'C:/Users/kpan/AppData/Local/Temp/Rtmp4GAMsN/Rinst21705ae349a4/PTXQC'
      -----------------------------------
ERROR: package installation failed
Error: Command failed (1)

**Comment by cbielow** [comment]
Your evidence.txt seems to contain unexpected data (could be due to a newer MaxQuant, or some setting which PTXQC was never tested with).

Multiple options so solve this:
1) send me the evidence.txt, so I can fix the bug. I can usually do that within 24h.
2) you could just rename evidence.txt, which will cause PTXQC to ignore all metrics which require it. But you will loose most of the valuable metrics this way. Unfortunately, there is currently no way to disable single metrics (soon to come).

3) edit the `fcn_computeQC.R` file in the PTXQC package after you've installed it using install_github() and remove or comment out this line
https://github.com/cbielow/PTXQC/blob/master/R/fcn_computeQC.R#L547

If possible, we should follow option 1, since the bug might affect other users as well. If the file contains sensitive data, you can upload it somewhere (maybe even password protected), and send the link just to me (and not use this issue tracker).

hope this helps.
cheers
Chris

**Comment by Leo838** [comment]
Dear Chris,

thanks a lot for your reply.
This dataset was processed using MaxQuant 1.5.2.8, which is actually the
same version used for other datasets that went through PTXQC smoothly. The
format of their evidence files should be the same.
The evidence is >2.5 GB. Would it be a problem?
I am looking for the best way transferring it. Meanwhile, probably you can
check the attached pdf? It contains all the names of the columns in the
evidence file.

Thanks again.
Best,
Kuan-Ting


2017-02-16 11:54 GMT+01:00 Chris Bielow <notifications@github.com>:

**Comment by Leo838** [comment]
Thanks. I will send you the evidence.txt file. 
Meanwhile, I have tried the second option. Than it appeared the error message as following: 

Starting to work on MSMS: %s ...
Error in !df_msms$contaminant : invalid argument type
Press any key to continue . . .

**Comment by cbielow** [comment]
https://gist.github.com/cbielow/5e8243eef611ba2f39d9f7d0f40cbb25

**Comment by cbielow** [comment]
before sending the whole file, you can try to copy only the first 100 lines or so.
If you have access to a linux console, thats easy to do using 'head -n 100 evidence.txt > evidence_chunk.txt'
This does not work on a Windows out-of-the-box, but the tools (inkl. head.exe) can be downloaded from e.g. http://unxutils.sourceforge.net/

I'd recommend to compress (zip) the file -- should reduce the size significantly.

You can mail me the small chunk or a link to the uploaded file.
my mail is 'chris.bielow [at here]  fu-berlin.de'

It seems you were lucky enough to find a second bug in msms.txt. So that would also be nice to have :)

**Comment by cbielow** [comment]
PTXQC is fixed (v0.82.2), please give it another go.
(the CRAN version should be up shortly as well)

You can now also customize which metrics are computed (via the `order` section in the YAML file), see
https://github.com/cbielow/PTXQC/blob/master/vignettes/PTXQC-CustomizeReport.Rmd

**Comment by Leo838** [comment]
It works. You are SUPER!

**Comment by cbielow** [comment]
glad to hear to works.
