### ISSUE TITLE
error: cannot open file `Rplots.pdf` 

### ISSUE THREAD

**Issue by MiguelCos** [cbielow/PTXQC#82]
Hello,

We are having some issues to run our PTXQC analysis using the drag n drop batch file.

I installed the new version in our server, in a folder that is accessible for everyone and all users with access to this folder should have writing rights.

I am one of the server admins and I am able the execute the script with no issues, but other users with the same admin rights are not able to generate any reports.

The error is presented as follows:

![image (1)](https://user-images.githubusercontent.com/33185213/86244139-cc50c780-bba7-11ea-876e-fa9d981cb4bd.png)

It seems to be related with this `Rplots.pdf` file that is created at some point during the analysis, but I am not able to diagnose the core issue in order to solved and make the script useful for every user in the server. 

I hope someone could have an idea of what could be happening here and how to solve it.

Best wishes,
Miguel

**Comment by cbielow** [comment]
Hi Miguel,

sorry, I missed the post when you posted it.
I have written a fix, which hopefully resolved the issue.

It is available in the current GitHub version of PTXQC, or will be available soon on CRAN as PTXQC v1.0.7.

The reason you are seeing this error is probably because some code deep down in some dependent package tries to create a default PDF device (rplots.pdf), but fails to do so, because it cannot write to the path it likes to (whereever that may be -- I would hope the TEMP directory). So maybe some of the environment variables in your users setup are a bit off, but I cannot say for sure.

The other way to fix this, is to create a predefined PDF device, so R does not need to come up with a faulty default one.
This is what was done here.

I hope this helps.

Please reopen if the issue persists.
