### ISSUE TITLE
Error pandoc

### ISSUE THREAD

**Issue by DaliJarboui** [cbielow/PTXQC#89]
Dear developer, 
I followed your installation steps to the word for windows, however when trying to use PTXQC, I receive an error that pandoc.exe is missing, 
I installed pandoc for windows (pandoc-2.11.1.1-windows-x86_64.msi) and retrieved the doc containing pandoc copied it as you detailed, and still I receive an error about pandoc missing.
is there a dependency to a specific version of pandoc ??.
appreciate your help
regards

**Comment by cbielow** [comment]
The pandoc installer should(?) have made pandoc available within R.
Well... seems that did not work.

Some ideas to fix this:
1) make sure `pandoc.exe` is found globally in a commandline/console/terminal, i.e.
```
c:\>where pandoc
```
should give something like
```
C:\Program Files\RStudio\bin\pandoc\pandoc.exe
```

If that is not the case, then add the path to pandoc.exe (in my case `C:\Program Files\RStudio\bin\pandoc` to your $PATH variable) and make sure to restart the console or any other application afterwards so they use the updated PATH.


2) within `R`, try
```
> rmarkdown::pandoc_available()
[1] TRUE
```

this should return TRUE. If it does, then PTXQC should also run fine. Do this is the same R session, that is used for PTXQC, in particular not in RStudio (which is a wrapper around a plain R console because it adds more enviroment variables, which might make pandoc available, even though it would be missing in a plain R console).


Hope this helps.
Let me know if this fixes it.
Good luck :)
