### ISSUE TITLE
MissedCleavages plot missing

### ISSUE THREAD

**Issue by cbielow** [cbielow/PTXQC#90]
in v1.0.7 the MC plot is not shown anymore, but to a bug introduced in Sep. 2020 here:
https://github.com/cbielow/PTXQC/commit/803ebe3962d4e523dfddb54b2247ca851893d708

Thanks to Georg for reporting this!

**Comment by cbielow** [comment]
Solutions: wait for version 1.0.8 or revert to 1.0.4

**Comment by fabianegli** [comment]
Sorry to nag, but do you have a timeline for the release of version 1.0.8?

**Comment by cbielow** [comment]
I was planning to incorporate another thing I'm working on... bit this may only be ready in a month or so.
You can also install via `install_github(...)` -- see installation page. This will give you the current development version, which contains the fix.
If thats not an option, I'll do a release.

**Comment by fabianegli** [comment]
Thank you for the reply. Yes, I already already make use of the current master, just thought it would be nice to have this released.

On another note - maybe worth a separate issue - the version indicated form the current master it already uses te 1.0.8 version number although it obviously is something like 1.0.8dev.

Just to state the obvious. Anyone getting the Package from CRAN now will lack the missed cleavage report. Because it is an important part of the quality assessment I think it is worth releasing this simple bugfix fast instead of waiting for the implementation of new functionality, IMHO.

**Comment by cbielow** [comment]
> On another note - maybe worth a separate issue - the version indicated form the current master is indicated in the report filename and it already uses the 1.0.8 version number although it obviously is something like 1.0.8dev.

Exactly my thoughts! However, the R package building code thinks that `1.0.8xxx` is not a valid version number. It NEEDS semantic versioning. No more, no less. It's a shame.

> 
> Just to state the obvious. Anyone getting the Package from CRAN now will lack the missed cleavage report. Because it is an important part of the quality assessment I think it is worth releasing this simple bugfix fast instead of waiting for the implementation of new functionality, IMHO.

There is another side of the coin: CRAN maintainers will complain if you release too often (true story). So I tend to wait for at least 2 months, but I'll try a release soon.

**Comment by fabianegli** [comment]
Hmmm ... strange thing this R-verse. Thank you for your very informative reply and work on this package.

**Comment by fabianegli** [comment]
Well, after reading through some of the R package development documentation it becomes clear that they are not encouraging short release cycles because it means a lot of manual curation for them - which probably is intended to keep a high standard fro packages on CRAN. A two edged sword as seen in this case. 

A thought on the release numbering. To prevent the "missing" dev versions, you could use even numbers o the patch level for releases that go to CRAN and uneven numbers for code that is in development or vice versa. Just a thought.

**Comment by cbielow** [comment]
Release 1.0.8 is on CRAN now (as well as on GitHub, obviously)

**Comment by fabianegli** [comment]
Thank you!

**Comment by cbielow** [comment]
> A thought on the release numbering. To prevent the "missing" dev versions, you could use even numbers on the patch level for releases that go to CRAN and uneven numbers for code that is in development or vice versa. Just a thought.

with `missing dev versions` you mean versions missing from CRAN?
Not sure that even/odd scheme would help there, because people would have to know about this to benefit from the approach. Ok, you can argue that the schema is kind of obvious... :)
But what if I do two Github-only releases in a row? This would mean trouble...
So for now, I'll just keep tagging each version as appropriate until we find a solution which has less drawbacks. Not a big problem at the moment IMHO.

**Comment by fabianegli** [comment]
With the *missing dev versions* I meant that you can't use versions like `1.0.0dev`. For two consecutive GitHub only releases you could just skip the in-between even number that would have been used for a release on CRAN. 

The benefit of it would be that if there is a version number of a version released on CRAN in the report file name it can not be from a pre-release development version that carried the same version string.

**Comment by fabianegli** [comment]
Presumably, the vast majority of users is not affected by this versioning issue because they use the CRAN releases exclusively. This means it is not a very impactful issue, but on the other hand I think you only have to increase the version number by one before each release to CRAN which is simple and quick to do IMHO.
